import re
import requests

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
}

COUNTRY_CODES = {
    "1": {"country": "US/Canada", "region": "North America"},
    "7": {"country": "Russia/Kazakhstan", "region": "Asia/Europe"},
    "20": {"country": "Egypt", "region": "Africa"},
    "27": {"country": "South Africa", "region": "Africa"},
    "30": {"country": "Greece", "region": "Europe"},
    "31": {"country": "Netherlands", "region": "Europe"},
    "32": {"country": "Belgium", "region": "Europe"},
    "33": {"country": "France", "region": "Europe"},
    "34": {"country": "Spain", "region": "Europe"},
    "36": {"country": "Hungary", "region": "Europe"},
    "39": {"country": "Italy", "region": "Europe"},
    "40": {"country": "Romania", "region": "Europe"},
    "41": {"country": "Switzerland", "region": "Europe"},
    "43": {"country": "Austria", "region": "Europe"},
    "44": {"country": "United Kingdom", "region": "Europe"},
    "45": {"country": "Denmark", "region": "Europe"},
    "46": {"country": "Sweden", "region": "Europe"},
    "47": {"country": "Norway", "region": "Europe"},
    "48": {"country": "Poland", "region": "Europe"},
    "49": {"country": "Germany", "region": "Europe"},
    "51": {"country": "Peru", "region": "South America"},
    "52": {"country": "Mexico", "region": "North America"},
    "54": {"country": "Argentina", "region": "South America"},
    "55": {"country": "Brazil", "region": "South America"},
    "56": {"country": "Chile", "region": "South America"},
    "57": {"country": "Colombia", "region": "South America"},
    "58": {"country": "Venezuela", "region": "South America"},
    "60": {"country": "Malaysia", "region": "Asia"},
    "61": {"country": "Australia", "region": "Oceania"},
    "62": {"country": "Indonesia", "region": "Asia"},
    "63": {"country": "Philippines", "region": "Asia"},
    "64": {"country": "New Zealand", "region": "Oceania"},
    "65": {"country": "Singapore", "region": "Asia"},
    "66": {"country": "Thailand", "region": "Asia"},
    "81": {"country": "Japan", "region": "Asia"},
    "82": {"country": "South Korea", "region": "Asia"},
    "84": {"country": "Vietnam", "region": "Asia"},
    "86": {"country": "China", "region": "Asia"},
    "90": {"country": "Turkey", "region": "Asia/Europe"},
    "91": {"country": "India", "region": "Asia"},
    "92": {"country": "Pakistan", "region": "Asia"},
    "93": {"country": "Afghanistan", "region": "Asia"},
    "94": {"country": "Sri Lanka", "region": "Asia"},
    "95": {"country": "Myanmar", "region": "Asia"},
    "98": {"country": "Iran", "region": "Asia"},
    "212": {"country": "Morocco", "region": "Africa"},
    "213": {"country": "Algeria", "region": "Africa"},
    "216": {"country": "Tunisia", "region": "Africa"},
    "218": {"country": "Libya", "region": "Africa"},
    "220": {"country": "Gambia", "region": "Africa"},
    "221": {"country": "Senegal", "region": "Africa"},
    "222": {"country": "Mauritania", "region": "Africa"},
    "223": {"country": "Mali", "region": "Africa"},
    "224": {"country": "Guinea", "region": "Africa"},
    "225": {"country": "Ivory Coast", "region": "Africa"},
    "226": {"country": "Burkina Faso", "region": "Africa"},
    "227": {"country": "Niger", "region": "Africa"},
    "228": {"country": "Togo", "region": "Africa"},
    "229": {"country": "Benin", "region": "Africa"},
    "230": {"country": "Mauritius", "region": "Africa"},
    "231": {"country": "Liberia", "region": "Africa"},
    "232": {"country": "Sierra Leone", "region": "Africa"},
    "233": {"country": "Ghana", "region": "Africa"},
    "234": {"country": "Nigeria", "region": "Africa"},
    "235": {"country": "Chad", "region": "Africa"},
    "236": {"country": "CAR", "region": "Africa"},
    "237": {"country": "Cameroon", "region": "Africa"},
    "238": {"country": "Cape Verde", "region": "Africa"},
    "239": {"country": "Sao Tome", "region": "Africa"},
    "240": {"country": "Equatorial Guinea", "region": "Africa"},
    "241": {"country": "Gabon", "region": "Africa"},
    "242": {"country": "Congo", "region": "Africa"},
    "243": {"country": "DR Congo", "region": "Africa"},
    "244": {"country": "Angola", "region": "Africa"},
    "245": {"country": "Guinea-Bissau", "region": "Africa"},
    "246": {"country": "Diego Garcia", "region": "Asia"},
    "247": {"country": "Ascension", "region": "Africa"},
    "248": {"country": "Seychelles", "region": "Africa"},
    "249": {"country": "Sudan", "region": "Africa"},
    "250": {"country": "Rwanda", "region": "Africa"},
    "251": {"country": "Ethiopia", "region": "Africa"},
    "252": {"country": "Somalia", "region": "Africa"},
    "253": {"country": "Djibouti", "region": "Africa"},
    "254": {"country": "Kenya", "region": "Africa"},
    "255": {"country": "Tanzania", "region": "Africa"},
    "256": {"country": "Uganda", "region": "Africa"},
    "257": {"country": "Burundi", "region": "Africa"},
    "258": {"country": "Mozambique", "region": "Africa"},
    "260": {"country": "Zambia", "region": "Africa"},
    "261": {"country": "Madagascar", "region": "Africa"},
    "262": {"country": "Reunion", "region": "Africa"},
    "263": {"country": "Zimbabwe", "region": "Africa"},
    "264": {"country": "Namibia", "region": "Africa"},
    "265": {"country": "Malawi", "region": "Africa"},
    "266": {"country": "Lesotho", "region": "Africa"},
    "267": {"country": "Botswana", "region": "Africa"},
    "268": {"country": "Eswatini", "region": "Africa"},
    "269": {"country": "Comoros", "region": "Africa"},
    "290": {"country": "Saint Helena", "region": "Africa"},
    "291": {"country": "Eritrea", "region": "Africa"},
    "297": {"country": "Aruba", "region": "Caribbean"},
    "298": {"country": "Faroe Islands", "region": "Europe"},
    "299": {"country": "Greenland", "region": "North America"},
    "350": {"country": "Gibraltar", "region": "Europe"},
    "351": {"country": "Portugal", "region": "Europe"},
    "352": {"country": "Luxembourg", "region": "Europe"},
    "353": {"country": "Ireland", "region": "Europe"},
    "354": {"country": "Iceland", "region": "Europe"},
    "355": {"country": "Albania", "region": "Europe"},
    "356": {"country": "Malta", "region": "Europe"},
    "357": {"country": "Cyprus", "region": "Europe"},
    "358": {"country": "Finland", "region": "Europe"},
    "359": {"country": "Bulgaria", "region": "Europe"},
    "370": {"country": "Lithuania", "region": "Europe"},
    "371": {"country": "Latvia", "region": "Europe"},
    "372": {"country": "Estonia", "region": "Europe"},
    "373": {"country": "Moldova", "region": "Europe"},
    "374": {"country": "Armenia", "region": "Asia"},
    "375": {"country": "Belarus", "region": "Europe"},
    "376": {"country": "Andorra", "region": "Europe"},
    "377": {"country": "Monaco", "region": "Europe"},
    "378": {"country": "San Marino", "region": "Europe"},
    "380": {"country": "Ukraine", "region": "Europe"},
    "381": {"country": "Serbia", "region": "Europe"},
    "382": {"country": "Montenegro", "region": "Europe"},
    "383": {"country": "Kosovo", "region": "Europe"},
    "385": {"country": "Croatia", "region": "Europe"},
    "386": {"country": "Slovenia", "region": "Europe"},
    "387": {"country": "Bosnia", "region": "Europe"},
    "389": {"country": "North Macedonia", "region": "Europe"},
    "420": {"country": "Czech Republic", "region": "Europe"},
    "421": {"country": "Slovakia", "region": "Europe"},
    "423": {"country": "Liechtenstein", "region": "Europe"},
    "500": {"country": "Falkland Islands", "region": "South America"},
    "501": {"country": "Belize", "region": "Central America"},
    "502": {"country": "Guatemala", "region": "Central America"},
    "503": {"country": "El Salvador", "region": "Central America"},
    "504": {"country": "Honduras", "region": "Central America"},
    "505": {"country": "Nicaragua", "region": "Central America"},
    "506": {"country": "Costa Rica", "region": "Central America"},
    "507": {"country": "Panama", "region": "Central America"},
    "508": {"country": "Saint Pierre", "region": "North America"},
    "509": {"country": "Haiti", "region": "Caribbean"},
    "590": {"country": "Guadeloupe", "region": "Caribbean"},
    "591": {"country": "Bolivia", "region": "South America"},
    "592": {"country": "Guyana", "region": "South America"},
    "593": {"country": "Ecuador", "region": "South America"},
    "594": {"country": "French Guiana", "region": "South America"},
    "595": {"country": "Paraguay", "region": "South America"},
    "596": {"country": "Martinique", "region": "Caribbean"},
    "597": {"country": "Suriname", "region": "South America"},
    "598": {"country": "Uruguay", "region": "South America"},
    "599": {"country": "Dutch Caribbean", "region": "Caribbean"},
    "670": {"country": "East Timor", "region": "Asia"},
    "672": {"country": "Antarctica", "region": "Antarctica"},
    "673": {"country": "Brunei", "region": "Asia"},
    "674": {"country": "Nauru", "region": "Oceania"},
    "675": {"country": "Papua New Guinea", "region": "Oceania"},
    "676": {"country": "Tonga", "region": "Oceania"},
    "677": {"country": "Solomon Islands", "region": "Oceania"},
    "678": {"country": "Vanuatu", "region": "Oceania"},
    "679": {"country": "Fiji", "region": "Oceania"},
    "680": {"country": "Palau", "region": "Oceania"},
    "681": {"country": "Wallis and Futuna", "region": "Oceania"},
    "682": {"country": "Cook Islands", "region": "Oceania"},
    "683": {"country": "Niue", "region": "Oceania"},
    "685": {"country": "Samoa", "region": "Oceania"},
    "686": {"country": "Kiribati", "region": "Oceania"},
    "687": {"country": "New Caledonia", "region": "Oceania"},
    "688": {"country": "Tuvalu", "region": "Oceania"},
    "689": {"country": "French Polynesia", "region": "Oceania"},
    "690": {"country": "Tokelau", "region": "Oceania"},
    "691": {"country": "Micronesia", "region": "Oceania"},
    "692": {"country": "Marshall Islands", "region": "Oceania"},
    "850": {"country": "North Korea", "region": "Asia"},
    "852": {"country": "Hong Kong", "region": "Asia"},
    "853": {"country": "Macau", "region": "Asia"},
    "855": {"country": "Cambodia", "region": "Asia"},
    "856": {"country": "Laos", "region": "Asia"},
    "880": {"country": "Bangladesh", "region": "Asia"},
    "886": {"country": "Taiwan", "region": "Asia"},
    "960": {"country": "Maldives", "region": "Asia"},
    "961": {"country": "Lebanon", "region": "Asia"},
    "962": {"country": "Jordan", "region": "Asia"},
    "963": {"country": "Syria", "region": "Asia"},
    "964": {"country": "Iraq", "region": "Asia"},
    "965": {"country": "Kuwait", "region": "Asia"},
    "966": {"country": "Saudi Arabia", "region": "Asia"},
    "967": {"country": "Yemen", "region": "Asia"},
    "968": {"country": "Oman", "region": "Asia"},
    "970": {"country": "Palestine", "region": "Asia"},
    "971": {"country": "UAE", "region": "Asia"},
    "972": {"country": "Israel", "region": "Asia"},
    "973": {"country": "Bahrain", "region": "Asia"},
    "974": {"country": "Qatar", "region": "Asia"},
    "975": {"country": "Bhutan", "region": "Asia"},
    "976": {"country": "Mongolia", "region": "Asia"},
    "977": {"country": "Nepal", "region": "Asia"},
    "992": {"country": "Tajikistan", "region": "Asia"},
    "993": {"country": "Turkmenistan", "region": "Asia"},
    "994": {"country": "Azerbaijan", "region": "Asia"},
    "995": {"country": "Georgia", "region": "Asia"},
    "996": {"country": "Kyrgyzstan", "region": "Asia"},
    "998": {"country": "Uzbekistan", "region": "Asia"},
}

def _analyze_number(phone):
    digits = re.sub(r'[^0-9]', '', phone)
    country_code = None
    country_name = "Unknown"
    region = "Unknown"
    line_type = "Unknown"
    if digits.startswith("1") and len(digits) == 11:
        country_code = "1"
    elif digits.startswith("7") and len(digits) == 11:
        country_code = "7"
    else:
        for cc in sorted(COUNTRY_CODES.keys(), key=lambda x: -len(x)):
            if digits.startswith(cc) and len(digits) >= len(cc) + 6:
                country_code = cc
                break
    if country_code and country_code in COUNTRY_CODES:
        country_name = COUNTRY_CODES[country_code]["country"]
        region = COUNTRY_CODES[country_code]["region"]
    if not country_code:
        country_code = "UNKNOWN"
    national_number = digits[len(country_code):] if country_code != "UNKNOWN" else digits
    if digits.startswith("80") or digits.startswith("90") or digits.startswith("84"):
        line_type = "Possible mobile/VoIP"
    elif digits.startswith("1") and len(digits) == 11:
        line_type = "NANP number"
    return {
        "raw_input": phone,
        "digits": digits,
        "digit_count": len(digits),
        "country_code": f"+{country_code}" if country_code != "UNKNOWN" else "UNKNOWN",
        "country": country_name,
        "region": region,
        "national_number": national_number,
        "line_type": line_type,
        "valid_format": len(digits) >= 7 and len(digits) <= 15,
    }

def lookup_phone(phone):
    phone = phone.strip()
    analysis = _analyze_number(phone)
    return analysis
